### ISSUE TITLE
Fails with SMAPI 3.9.5 because of missing method EnvironmentUtility.IsMono

### ISSUE THREAD

**Issue by tamas-kozma** [Pathoschild/StardewXnbHack#10]
SMAPI has removed some "unused" methods in the 3.9.5 release. `EnvironmentUtility.IsMono` was one of them, which, unfortunately, is in use here. Luckily the method is pretty trivial and can be easily added as a local extension method.

**Comment by Pathoschild** [comment]
Fixed via #11 for the upcoming StardewXnbHack 1.0.4. Thanks!
