### ISSUE TITLE
Something went wrong running the unpacker

### ISSUE THREAD

**Issue by HazeSystem** [Pathoschild/StardewXnbHack#12]
Got this error on latest SMAPI (3.12.7), game version 1.5.4, XnbHack 1.0.5. Tested 1.0.4 and it works fine.

`Oops! Something went wrong running the unpacker:
System.BadImageFormatException: Could not load file or assembly 'Stardew Valley, Version=1.3.37.0, Culture=neutral, PublicKeyToken=null'. An attempt was made to load a program with an incorrect format.
File name: 'Stardew Valley, Version=1.3.37.0, Culture=neutral, PublicKeyToken=null'
   at StardewXnbHack.Program.Run
   at StardewXnbHack.Program.Main()`

**Comment by Pathoschild** [comment]
Hi! The prerelease StardewXnbHack 1.0.5 is for Stardew Valley 1.5.5; using StardewXnbHack 1.0.4 instead should fix your error.
