### ISSUE TITLE
can't get it to work

### ISSUE THREAD

**Issue by Gubbleowo** [Pathoschild/StardewXnbHack#17]
I downloaded the program and unzipped it into the correct file (at least I'm pretty sure it is according to what the wiki says) but when I try to activate it, it says that it needs to be placed in the stardew valley game folder. 
For reference, I downloaded the Windows file and put it in the local files that you can access from Steam (if I'm not supposed to put it there I apologize for the stupid issue report).

**Comment by Pathoschild** [comment]
Hi! Make sure you put the files directly inside the game folder, so `StardewXnbHack.exe` is in the same folder as `Stardew Valley.exe`. It won't work if you have a `StardewXnbHack` folder inside the game folder.

If that's what you have, can you post a screenshot of your game folder?

**Comment by Gubbleowo** [comment]
![Screenshot (1)](https://github.com/Pathoschild/StardewXnbHack/assets/139273940/0e65548f-9e84-421c-af74-f46ed0e71ad7)

sorry I was having issues taking a screenshot but this is where I've been putting the file

**Comment by Pathoschild** [comment]
You'll need to move the files inside that `StardewXhbHack-1.0.7-for-Windows` folder up, so they're directly in the game folder.

**Comment by Gubbleowo** [comment]
it worked! wow now I feel dumb, Thanks for the help, and sorry if I bothered you.

**Comment by Pathoschild** [comment]
Welcome! I'll look into detecting that case to show a more specific error in upcoming versions.
