### ISSUE TITLE
Crashes immediately after running

### ISSUE THREAD

**Issue by sharksdudes** [Pathoschild/StardewXnbHack#18]
I extracted the file, copied the files into the game directory and ran them, the windows command appeared for a few seconds and then crashed and nothing else happened, tried opening a shell on the folder so it wouldn't crash and all it says it's loading, and then prompts me to input another command but nothing happens. Not sure if I missed something glaringly obvious or if it's just not working right now

**Comment by Pathoschild** [comment]
Does that still happen with the latest StardewXnbHack 1.1.0? If so, can you post a screenshot of what you see when launching it from the shell?
