### ISSUE TITLE
unsupported asset type

### ISSUE THREAD

**Issue by hhharkness** [Pathoschild/StardewXnbHack#20]
not an issue for me personally, but in care it's helpful to know i got these messages during the unpack:
Effects\ShadowRemove.xnb => Effect isn't a supported asset type.
Effects\ShadowRemoveMG3.8.0.xnb => Effect isn't a supported asset type.

**Comment by Pathoschild** [comment]
Hi! That's a known issue, since `Effects` are compiled code which can't be unpacked. You can use [xnb2shader](https://seancode.com/terrafirma/) to decompile them if needed though.
