### ISSUE TITLE
StardewXNBHack wont even open

### ISSUE THREAD

**Issue by Pixielart** [Pathoschild/StardewXnbHack#22]
File is in the correct place, SMAPI is fully updated. However, when I click the .exe nothing opens up. Nothing runs, nothing happens.

Smapi version 4.0.8

**Comment by Pathoschild** [comment]
Hi! See [_When I run StardewXnbHack, nothing happens or it quickly exits?_ in the readme](https://github.com/Pathoschild/StardewXnbHack?tab=readme-ov-file#when-i-run-stardewxnbhack-nothing-happens-or-it-quickly-exits) for help with that.
