### ISSUE TITLE
Unhandled Exception

### ISSUE THREAD

**Issue by Peepzilla** [Pathoschild/StardewXnbHack#23]
Stardew Valley version 1.6.8
SMAPI 4.0.8
StardewXNBHack 1.1.0

Error text as follows: 

> Found game folder: C:\Program Files (x86)\Steam\steamapps\common\Stardew Valley\.
> Loading game instance...
> 
> Unhandled exception: System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types.
> Method 'get_MinimumGameVersion' in type 'StardewModdingAPI.Toolkit.Serialization.Models.Manifest' from assembly 'SMAPI.Toolkit, Version=3.13.2.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
>    at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
>    at System.Reflection.Assembly.GetTypes()
>    at StardewValley.LocalMultiplayer.GetStaticFieldsAndDefaults() in D:\GitlabRunner\builds\Gq5qA5P4\0\ConcernedApe\stardewvalley\Farmer\Farmer\LocalMultiplayer.cs:line 121
>    at StardewValley.LocalMultiplayer.Initialize() in D:\GitlabRunner\builds\Gq5qA5P4\0\ConcernedApe\stardewvalley\Farmer\Farmer\LocalMultiplayer.cs:line 92
>    at StardewValley.GameRunner..ctor() in D:\GitlabRunner\builds\Gq5qA5P4\0\ConcernedApe\stardewvalley\Farmer\Farmer\LocalMultiplayer.cs:line 440
>    at StardewXnbHack.Program.CreateTemporaryGameInstance(PlatformContext platform, String contentPath) in /home/pathoschild/git/StardewXnbHack/StardewXnbHack/Program.cs:line 315
>    at StardewXnbHack.Program.Run(GameRunner game, String gamePath, Func`3 getLogger, Boolean showPressAnyKeyToExit) in /home/pathoschild/git/StardewXnbHack/StardewXnbHack/Program.cs:line 137
> System.TypeLoadException: Method 'get_MinimumGameVersion' in type 'StardewModdingAPI.Toolkit.Serialization.Models.Manifest' from assembly 'SMAPI.Toolkit, Version=3.13.2.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
> 
> Press any key to exit.

**Comment by Pathoschild** [comment]
Hi! You mentioned having SMAPI 4.0.8, but some of your SMAPI files are from an older version. You can reinstall SMAPI using its installer (not a mod manager like Vortex) to fix that.

**Comment by Peepzilla** [comment]
Yes, I actually did that twice - because the files showed the wrong number.
Did not use Vortex, and not sure what went wrong, but...

**Comment by Pathoschild** [comment]
If it still doesn't work for you, can you come ask in [#modded-game-support on the Stardew Valley Discord](https://smapi.io/community#Discord) so we can run some tests? Feel free to ping me there with `@pathoschild` if you don't get an answer.
