### ISSUE TITLE
Running StardewXNBHack on MacOS gives me a "too many symbolic links" error message

### ISSUE THREAD

**Issue by feanne** [Pathoschild/StardewXnbHack#7]
Hi! I'm new to modding and github so I hope I am doing this issue submission correctly. I would like to view the contents of Stardew XNB files, so I downloaded StardewXNBHack and unzipped it into my game folder so that "StardewXnbHack.exe" and "StardewXnbHack.command" are in the same folder as "StardewValley.exe".

When I double-clicked on "StardewXnbHack.command", I got this error, and no XNB files were unpacked:

<img width="897" alt="Screen Shot 2020-12-04 at 1 10 08 PM" src="https://user-images.githubusercontent.com/14862008/101125823-18130b80-3635-11eb-801d-53423a89fa12.png">

(I am not sure if this is an issue with StardewXNBHack, or a user error on my part.)

**Comment by Pathoschild** [comment]
I fixed the path error via 5193c618c57bb0a802b3cf811d63409f39b6abc5 for the upcoming 1.0.2, and sent you a test build to try on Discord. Feel free to reply there if you still have any issues!

(I'm not sure what's causing the "too many levels of symbolic links" messages, but they don't seem to be causing any issues.)
